before:
  hooks:
    - go mod tidy
builds:
  - id: owobot
    env:
      - CGO_ENABLED=0
    binary: owobot
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm64
      - arm
      - riscv64
archives:
  - files:
      - owobot.service
      - owobot.toml
nfpms:
  - id: owobot
    description: "Your server's guardian and entertainer"
    homepage: 'https://gitea.elara.ws/owobot/owobot'
    maintainer: 'Elara Musayelyan <elara@elara.ws>'
    license: AGPLv3
    formats:
      - deb
      - rpm
      - archlinux
    provides:
      - owobot
    conflicts:
      - owobot
    contents:
      - src: owobot.service
        dst: /etc/systemd/system/owobot.service
      - src: owobot.toml
        dst: /etc/owobot/config.toml
        type: "config|noreplace"
aurs:
  - name: owobot-bin
    homepage: 'https://gitea.elara.ws/owobot/owobot'
    description: "Your server's guardian and entertainer"
    maintainers:
      - 'Elara Musayelyan <elara@elara.ws>'
    license: AGPLv3
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/owobot-bin.git'
    provides:
      - owobot
    conflicts:
      - owobot
    backup:
      - etc/owobot/config.toml
    package: |-
      # binaries
      install -Dm755 ./owobot "${pkgdir}/usr/bin/owobot"

      # configs
      install -Dm644 ./owobot.toml "${pkgdir}/etc/owobot/config.toml"
      
      # services
      install -Dm644 ./owobot.service "${pkgdir}/etc/systemd/system/owobot.service"
release:
  gitea:
    owner: owobot
    name: owobot
announce:
  discord: 
    enabled: true
gitea_urls:
  api: 'https://gitea.elara.ws/api/v1/'
  download: 'https://gitea.elara.ws'
  skip_tls_verify: false
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc